;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        reindent-then-newline-and-indent
        ruby-electric-space
        ))

(setq mc/cmds-to-run-once
      '(
        cua-delete-region
        ruby-electric-curlies
        ruby-indent-line
        ))
