(source melpa)

(depends-on "auto-complete")
(depends-on "cask")
(depends-on "dash")
(depends-on "emmet-mode")
(depends-on "epl")
(depends-on "expand-region")
(depends-on "f")
(depends-on "guide-key")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "rinari")
(depends-on "robe")
(depends-on "s")
(depends-on "yasnippet")