(source melpa)

(depends-on "auto-complete")
(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "guide-key")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "robe")
(depends-on "s")